### ISSUE TITLE
Error in function

### ISSUE THREAD

**Issue by tusharjambhekar** [zemigpt/linux-disk-space-info#1]
disk_usage.sh: 16: disk_usage.sh: function: not found
disk_usage.sh: 17: local: not in a function

**Comment by zemigpt** [comment]
You probably aren't actually running under `bash` but rather `dash` or some other POSIX-compliant shell that does not recognize the function keyword.

Anyway, try removing the keyword 'function' and adding double parenthesis '()' after the function name, like this:

`function CalcCols {`

to

`CalcCols() {`
